### ISSUE TITLE
Custom HTML seems to not work.

### ISSUE THREAD

**Issue by rouilj** [jimniels/readlists#19]
I was testing out a copy of https://javascript-for-web-designers.abookapart.com. 

When I viewed the exported HTML, I found that I needed the following CSS to make it readable:
```css
img {
  max-width: 100%;
}
pre {
  outline: 1px black solid;
  padding: 1em;
  overflow: auto;
}
```

I then attempted to create a new copy of the HTML with the CSS placed inside the custom
HTML:
```html
<!DOCTYPE html>
<html>
<head>
<title>
Javascript for Web Designers -- Matt Marquis -- A Book Apart
</title>
<style>
<insert CSS from above here>
</style>
</head>
</html>
```
I regenerated the HTML and ended with the original title (not the one in the custom HTML)
and no style/css in the head.

Also when I:

1. saved the Readlist to json,
2. deleted the readlist and
3. reloaded the readlist from the json file I had saved

the custom html was not saved.

Am I doing something wrong?

The info dropdown identifies the version of readlists as  4dcaefb.
